# Generated by Django 6.0.1 on 2026-02-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
